"""Initial migration

Revision ID: de2293de8a1a
Revises: 
Create Date: 2020-02-08 22:53:07.945877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2293de8a1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=False),
    sa.Column('class_start_time', sa.Integer(), nullable=False),
    sa.Column('class_end_time', sa.Integer(), nullable=False),
    sa.Column('class_building', sa.Text(), nullable=False),
    sa.Column('class_room_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('homeworks',
    sa.Column('homeworks_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('homework_title', sa.Integer(), nullable=False),
    sa.Column('homework_due_date', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('homeworks_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    op.drop_table('classes')
    # ### end Alembic commands ###
